config/routes.rb
Rails.application.routes.draw do

  get 'raw/trulia'      => 'raw_trulia#show'
  get 'searchaddresses' => 'staticpages#officialaddresses'
  get 'testarea'     => 'staticpages#static_map_test_area'

  root 'daycareprovider#show'
  get 'search'          => 'daycareprovider#search'
  get ':id'            => 'neighborhoods#show'

end

app/models/ccsf_raw_feb19.rb
class CcsfRawFeb19 < ActiveRecord::Base
end

app/models/daycarelicense.rb
class Daycarelicense < ActiveRecord::Base
	validates :ccsf_license_id, 
		uniqueness: {:message => "id: %{value}" }

	belongs_to :daycareprovider, foreign_key: "day_care_provider_id"



end

app/models/daycareprovider.rb
class Daycareprovider < ActiveRecord::Base
	validates :day_care_provider_id, 
				uniqueness: {:scope => :contact_name, :message => "id: %{value}" }

	belongs_to :neighborhood
	has_many :daycarelicenses, foreign_key: "day_care_provider_id", primary_key: "day_care_provider_id"

	def number_of_licenses(id)
		return Daycarelicense.where(day_care_provider_id: id).size
	end

	def capacity(dcp_id)
		licenses = Daycarelicense.where(day_care_provider_id: id)
		capacity = 0
		license.each do |l|
			capacity =+ l.capacity 
		end 
	end 

	def age_range
		temp_range = self[:licensed_ages].split(",")
		range = "#{temp_range[0].to_i/12}-#{temp_range.last.to_i/12}"
		return range
	end

	# before_save :return_dupe_message

	# def return_dupe_message 
	# 	puts "hello"
	# 	if self.invalid?
	# 		puts self.errors[:uniqueness]
	# 	end 
	# end

end

app/models/daycareschedulehour.rb
class Daycareschedulehour < ActiveRecord::Base
	validates :ccsf_schedulehour_id, 
				uniqueness: {:message => "id: %{value}" }

end

app/models/dss_ca_gov_day_care_raw.rb
class DssCaGovDayCareRaw < ActiveRecord::Base
	validates :facilitynumber, uniqueness: true

	CONST_INFANT_CENTER = "0-2"
	CONST_FAMILY_DAY_CARE_HOME = "0-1O"
	CONST_SCHOOL_AGE_DAY_CARE_CENTER = "5-17" 
	DAY_CARE_CENTER = "2-5"

	def telephone
		temp = self[:telephone]
		# return temp
		return temp.gsub(/[()]/,'')
	end 

	def age_range
		if self[:facilitytype] = "INFANT CENTER"
			return CONST_INFANT_CENTER
		elsif 
			self[:facilitytype] = "FAMILY DAY CARE HOME"
			return CONST_FAMILY_DAY_CARE_HOME
		elsif 
			self[:facilitytype] = "SCHOOL AGE DAY CARE CENTER"
			return CONST_SCHOOL_AGE_DAY_CARE_CENTER
		elsif
			self[:facilitytype] = "DAY CARE CENTER"
			return DAY_CARE_CENTER
		end	
	end 
end

app/models/ingested_trulia_property.rb
class IngestedTruliaProperty < ActiveRecord::Base
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
	validates :neighborhood_name, uniqueness: true

	has_many :daycareproviders
	has_many :realdaycareproviders

	def day_care_count(id)
		return Daycareprovider.where(neighborhood_id: id).size
	end 

end

app/models/official_address.rb
class OfficialAddress < ActiveRecord::Base
	# include PgSearch
	# pg_search_scope :search_official_addresses, against: [:address]
		# ,
		# using: {
		# 	tsearch: { prefix: true}
		# }


end

app/models/realdaycareprovider.rb
class Realdaycareprovider < ActiveRecord::Base

	belongs_to :neighborhood

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/daycareprovider_controller.rb
class DaycareproviderController < ApplicationController


	def show
		@daycareproviders = Realdaycareprovider.all.limit(50).order("RANDOM()")
		@neighborhood_link_content = Neighborhood.all.limit(60).order("RANDOM()")
	end 

	def search 
		user_input 				= params[:searchinput]
		@daycareproviders 		= Realdaycareprovider.where(zip_code: user_input)
		@u_input 				= user_input
	end 


end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

	def show 
		@daycareproviders 	= Neighborhood.where(slug: params[:id]).first.realdaycareproviders
		@ngb_name 			= Neighborhood.where(slug: params[:id]).first.neighborhood_name
		@neighborhood_link_content = Neighborhood.all.limit(60).order("RANDOM()")
		render template: "daycareprovider/neighborhood_show"
	end 


end

app/controllers/raw_trulia_controller.rb
class RawTruliaController < ApplicationController

	def show
		@trulia_properties = IngestedTruliaProperty.all
		@temp = "helloasdfads"
		render "raw_trulia/show_raw_trulia_data"
	end 
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

	def home_page
		@neighborhoods = Neighborhood.all
	end 

	# def officialaddresses #api endpoint for the crappy jquery autocomplete
		# if params[:searchterm]
			# @officialaddresses = OfficialAddress.search_official_addresses(params[:searchterm])
			# render json: @officialaddresses
		# else
			# @officialaddresses = OfficialAddress.first(5)
		# end 		
	# end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daycareprovider_helper.rb
module DaycareproviderHelper
end

app/helpers/neighborhood_helper.rb
module NeighborhoodHelper
end

app/helpers/raw_trulia_helper.rb
module RawTruliaHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/daycareprovider/_neighborhood_links_table.erb
<% content_for :neighborhood_links do %>
        <section id="neighborhoods_list">
          <div id="neighborhood_links_title">Neighborhoods </div>
          <!-- <div class="container"> -->
            <div class="row soace3" id="neighborhood_links">
              <% @neighborhood_link_content.each do |nlc | %>
                <% if @neighborhood_link_content.count % 4 == 0 %>
                  <div class="col-md-3 col-sm-6 col-xs-12">  
                <% end %>                
                  <div class="neighborhood_ahrefs"><a href="/<%= nlc.slug %>"><%= nlc.neighborhood_name %></div></a>
                <% if @neighborhood_link_content.count % 4 == 0 %>
                  </div>
                <% end %>
              <% end %>
            </div>
          <!-- </div> -->
        </section>
<% end %>

app/views/daycareprovider/_resultstable.html.erb
<table class="table table-striped table-sm  table-responsive customt"> 
	<thead class="thead">
		<!-- <th></th> -->
		<th>Name</th>
		<th>Address</th>
		<!-- <th>Age</th> -->
		<th>Phone</th>
		<th>Email</th>
		<th>Type</th>
		<th>License</th>
	</thead>

	<% @daycareproviders.each_with_index do |provider, index| %>
		<tr>
			
			<td>
				<% if !provider.business_name.nil? %>
					<%= provider.business_name.titlecase %>
				<% else %>
					<%= provider.name.titlecase %>
				<% end %>
			</td>
			<td><%= provider.address.titlecase %></td>
			<td><%= number_to_phone(provider.phone) %></td>
			<td>
				<% if !provider.email.nil? && provider.email != "Unknown" %>
					<!-- # <%= provider.email %> -->
       				<div class="email_click">
      					<!-- <i class="fa fa-envelope-o" aria-hidden="true"></i> -->
      					email
      					<div class="hidden_provider_deets"><%= provider.email %></div>
      					<div class="hidden_provider_deets"><%= provider.name %></div>
      				</div> 
      			<% else %>
      				
      			<% end %>
			</td>
			<td>
				<%= provider.daycare_type.titlecase %>
			</td>
			<td>
				<a target="_blank" href="https://secure.dss.ca.gov/CareFacilitySearch/FacDetail/<%= provider.license_id_1 %>">
					<!-- <i class="fa fa-id-card-o" aria-hidden="true"></i> -->
					<%= provider.license_id_1 %>
				</a> 
				<% if !provider.license_id_2.blank? %>

					<a target="_blank" href="https://secure.dss.ca.gov/CareFacilitySearch/FacDetail/<%= provider.license_id_2 %>">
						<!-- <i class="fa fa-id-card-o" aria-hidden="true"></i> -->
						(<%= provider.license_id_2 %>)
					</a> 					
				<% end %>
			</td>

		</tr>
	<% end %>


</table> 


<div id="myModal" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="provider_modal_deets">Email Address</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><div id="provideremail">Modal body text goes here.</div></p>
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-primary">Got it, thanks!</button> -->
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Got it, thanks!</button>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
	emails = document.getElementsByClassName("email_click")
	for(i=0;i<emails.length;i++) {
		emails[i].addEventListener("click", function launch_modal(e) {
			console.log(e.currentTarget.lastElementChild.innerText);
			console.log(e.currentTarget.lastElementChild.previousElementSibling.innerText);
			
			// e.preventDefault();
			
			$("#provider_modal_deets").text(e.currentTarget.lastElementChild.innerText);
			$("#provideremail").text(e.currentTarget.lastElementChild.previousElementSibling.innerText);
			$("#myModal").modal({keyboard:true})
		
			// return false;	
		});		
	}

</script>
<div style="display:none;"><%= @total_daycare_count_after_deduping %></div>

app/views/daycareprovider/neighborhood_show.erb
<% content_for :head do %>
  <title>Day Cares in the <%= @ngb_name%>, San Francisco, CA 2017 </title>
  <meta name="description" content="Here is the definitive list of daycares in <%= @ngb_name%>, San Francisco, complete with phone numbers, emails and information on any violations or citations." />

<% end %>
<h3 id="neighborhood_header">Day Cares in the <%= @ngb_name%>, San Francisco</h3>
<a id="backlink" href="/">< Home</a>

<%= render 'daycareprovider/resultstable' %>
<%= render 'daycareprovider/neighborhood_links_table' %>

app/views/daycareprovider/search.html.erb
<div class="col" id="centerme_search">
		<div contenteditable="false" class="search">
  		<%= form_tag("/search", method: "get") do %>          
    		<input id="searchinput" type="text" name="searchinput" value=<%=@u_input %>>
  		<% end %>
	</div>
</div>
<a id="backlink" href="/">< back</a>
<div class="col" >
<%= render 'resultstable' %>
</div>

app/views/daycareprovider/show.html.erb
<% content_for :head do %>
  <title>Day Cares in San Francisco, CA 2017 </title>
  <meta name="description" content="Here is the definitive list of daycares in San Francisco, complete with phone numbers, emails and information on any violations or citations." />
<% end %>

<div class="col" id="centerme">
	<div id="searchtitle" class="center-block align-middle"> 
		San Francisco Day Care Directory
	</div>
		<div contenteditable="false" class="search center-block align-middle">
  		<%= form_tag("/search", method: "get") do %>          
    		<input id="searchinput" type="text" name="searchinput" placeholder="zip code...">
  		<% end %>
  		<div id="display" class="error"></div>
	</div>
  
</div>

<div class="col" >
<%= render 'daycareprovider/resultstable' %>

<%= render 'daycareprovider/neighborhood_links_table' %>
</div>

<script type="text/javascript">
	
	$('#searchinput').keyup(function() {
   		
   		if (isNaN($(this).val()))
   			$('#display').text("I need a zip code to give you results");
   		else
   			$('#display').text("");


	});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110222912-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-110222912-1');
  </script>
  <meta name="msvalidate.01" content="CDAFAD3FEFCEE036EC09FE7435EC5FD0" />
  <%= yield :head %>
  <title>List of Daycares in San Francisco</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<%= yield :head_stylesheets %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
  <!-- <script src="https://use.fontawesome.com/c4f865cc02.js"></script> -->
</head>

<body>


  <div class="container">
    <div class="row ">
    </div>

  	<div class="row">
      <div class="col">
  		  <%= yield %>     
      </div>
	 </div>     
   <div class="row">
     <div class="col">
        <%= yield :neighborhood_links %>

     </div>
   </div>
</div>
	
	
</body>
</html>

app/views/neighborhoods/old_neighborhood_show.html.erb
<% content_for :head do %>
  <title>Day Cares in <%= @ngb_name%>, San Francisco, CA 2017 </title>
  <meta name="description" content="Here is the definitive list of daycares in <%= @ngb_name%>, San Francisco, complete with phone numbers, emails and information on any violations or citations." />

<% end %>
<h3 id="header">Day Cares <%= @ngb_name%>, San Francisco</h3>

<% @dcps.each do |dcp| %>
	
	

<div class="card">
  <div class="card-block">
    <h4 class="card-title spacing">
      <div id="cardheadertext">
      <% if dcp.alternate_name.blank? %>
        <%= dcp.name %>
      <% else %> 
        <%= dcp.alternate_name %>
      <% end %> 
<!--         <span class="card-text rightsidecard">
          <span id="toplicense">
            <ul>
              <li><b>License:</b> <%= dcp.daycarelicenses.first.state_license_number %></li>
              <li><b>Capactiy:</b> <%=dcp.daycarelicenses.first.capacity %></li>
            </ul>
          <span>
            <% if dcp.daycarelicenses.size > 1 %>
          <span id="bottomlicense">
            <ul>
              <li><b>License: </b><%= dcp.daycarelicenses.second.state_license_number %></li>
              <li><b>Capactiy: </b><%=dcp.daycarelicenses.first.capacity %></li>
            </ul>
            <% end %>
          </span>
        </span>
      </div> -->

    </h4>

    <h6 class="card-subtitle mb-2 text-muted">
      <small class="text-muted">
        <% if dcp.alternate_name.blank? %>
        	 <%= dcp.address_1 %> <%= dcp.mail_zip_code %>
        <% else %>
        	<%= dcp.name %> @ <%= dcp.address_1 %> <%= dcp.mail_zip_code %>
       	<% end %>
      </small>
    </h6>

    <h6 class="card-subtitle mb-2 text-muted">
      <table id="table1">
        <tr>
          <td><%= dcp.daycarelicenses.first.capacity %></td>
          <td><%= dcp.daycarelicenses.first.vacancies %></td>
          <td><%= dcp.daycarelicenses.first.age_from_year %>-<%= dcp.daycarelicenses.first.age_to_year %></td>
        </tr>
        <tr class="tablelabels">
          <td>Capacity</td>
          <td>Vacancies</td>
          <td>Age (years)</td>
        </tr>
        

      </table>

    </h6>

    <p class="card-text"><%= dcp.description %></p>
    
    
    <div class="contactdeets">
      <span id="email"><%= number_to_phone(dcp.phone) %> </span>
      <span id="email2"><%= dcp.email %></span>
    </div>
    
    
  </div>
      <div  class="card-footer text-muted">
      <small>#<%= dcp.daycarelicenses.first.state_license_number %></small>
      <% if dcp.daycarelicenses.size > 1 %>
        <small>#<%= dcp.daycarelicenses.second.state_license_number %></small>
      <% end %>
    </div>

</div>	
<% end %>
<div id="footer"></div>

app/views/neighborhoods/show.html.erb
<% content_for :head do %>
  <title>Day Cares in <%= @ngb_name%>, San Francisco, CA 2017 </title>
  <meta name="description" content="Here is the definitive list of daycares in <%= @ngb_name%>, San Francisco, complete with phone numbers, emails and information on any violations or citations." />

<% end %>
<h3 id="header">Day Cares <%= @ngb_name%>, San Francisco</h3>

<% @dcps.each do |dcp| %>
	
	

<div class="card">
  <div class="card-block">
    <h4 class="card-title spacing">
      <div id="cardheadertext">
      <% if dcp.alternate_name.blank? %>
        <%= dcp.name %>
      <% else %> 
        <%= dcp.alternate_name %>
      <% end %> 
<!--         <span class="card-text rightsidecard">
          <span id="toplicense">
            <ul>
              <li><b>License:</b> <%= dcp.daycarelicenses.first.state_license_number %></li>
              <li><b>Capactiy:</b> <%=dcp.daycarelicenses.first.capacity %></li>
            </ul>
          <span>
            <% if dcp.daycarelicenses.size > 1 %>
          <span id="bottomlicense">
            <ul>
              <li><b>License: </b><%= dcp.daycarelicenses.second.state_license_number %></li>
              <li><b>Capactiy: </b><%=dcp.daycarelicenses.first.capacity %></li>
            </ul>
            <% end %>
          </span>
        </span>
      </div> -->

    </h4>

    <h6 class="card-subtitle mb-2 text-muted">
      <small class="text-muted">
        <% if dcp.alternate_name.blank? %>
        	 <%= dcp.address_1 %> <%= dcp.mail_zip_code %>
        <% else %>
        	<%= dcp.name %> @ <%= dcp.address_1 %> <%= dcp.mail_zip_code %>
       	<% end %>
      </small>
    </h6>

    <h6 class="card-subtitle mb-2 text-muted">
      <table id="table1">
        <tr>
          <td><%= dcp.daycarelicenses.first.capacity %></td>
          <td><%= dcp.daycarelicenses.first.vacancies %></td>
          <td><%= dcp.daycarelicenses.first.age_from_year %>-<%= dcp.daycarelicenses.first.age_to_year %></td>
        </tr>
        <tr class="tablelabels">
          <td>Capacity</td>
          <td>Vacancies</td>
          <td>Age (years)</td>
        </tr>
        

      </table>

    </h6>

    <p class="card-text"><%= dcp.description %></p>
    
    
    <div class="contactdeets">
      <span id="email"><%= number_to_phone(dcp.phone) %> </span>
      <span id="email2"><%= dcp.email %></span>
    </div>
    
    
  </div>
      <div  class="card-footer text-muted">
      <small>#<%= dcp.daycarelicenses.first.state_license_number %></small>
      <% if dcp.daycarelicenses.size > 1 %>
        <small>#<%= dcp.daycarelicenses.second.state_license_number %></small>
      <% end %>
    </div>

</div>	
<% end %>
<div id="footer"></div>

app/views/raw_trulia/show_raw_trulia_data.html.erb
<div id="raw_trulia_content">
	<%= @temp %>
	<% @trulia_properties.each do |prop| %>
		<%= prop.inspect %>
		</br>
		</br>l;.
	<% end %> 
</div>

app/views/raw_trulia/trulia_raw.html.erb
<div id="test">adfs</div>
<%= @temp %>
<% @trulia_properties.each do |prop| %>
	<%= prop.inspect %>
	</br>
	</br>
<% end %> 

app/views/staticpages/home_page.html.erb
<!-- <%= debug @officialaddresses %> -->
<!-- <form action="#" >
	<input type="text" class="form-control" id="officialAddressSearch" onkeypress="search(event)">
</form>
 -->
</br>
 <p>
 <!-- <select id="propertyautocomplete" class="js-example-responsive" style="width: 50%" placeholder="Look Up Address">
  -->	
 </select>
 </p>
 </br>

<!-- <a href="raw/trulia">Raw Trulia Data</a> -->

<!-- <script type="text/javascript">
	// $(document).ready(function() {
	$("#propertyautocomplete").select2({
		placeholder: "Find an address",
		allowClear: true,
		delay: 800,
		cache: true,
		ajax: {
			url: "/searchaddresses",
			dataType: 'json',
			data: function (params){
				return{ searchterm: params.term}
			},
			processResults: function(data){
				return {
        				results: $.map(data, function(obj) {
            				return { id: obj.id, text: obj.address };
        				})
    			};
			}

		}
	});
	// });


</script> -->

<% @neighborhoods.each_with_index do |dcp, index| %>

	<% if index % 2 == 0 %>
	<div class="row">

		<div class="col-sm-6">
			<div class="card">
			  <div class="card-block">
			    <h3 class="card-title"><%= link_to dcp.neighborhood_name, neighborhood_path(dcp.neighborhood_id) %></h3>
			    <p class="card-text">Daycares: <%= dcp.day_care_count(dcp.neighborhood_id) %></p>
			  </div>
			</div>
		</div>
	<% else %>
		<div class="col-sm-6">
			<div class="card">
			  <div class="card-block">
			    <h3 class="card-title"><%= link_to dcp.neighborhood_name, neighborhood_path(dcp.neighborhood_id) %></h3>
			    <p class="card-text">Daycares: <%= dcp.day_care_count(dcp.neighborhood_id) %>	</p>		   
			  </div>
			</div>
		</div>
	</div>
	<% end %>

<% end %>